import {readFile,writeFile,mkdir,copyFile,mkdtemp,rm,rename} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {loadArticles,escapeHtml as e} from './content.mjs';
import {templates} from './site-template.mjs';
import {validateSite} from './validate.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));process.chdir(root);
const c=JSON.parse(await readFile('site.config.json','utf8')),articles=await loadArticles('content/articles',['tutorials']),t=templates(c,articles),origin=c.origin;
const output=await mkdtemp(path.join(root,'.build-')),routes=[];
const para=(h,p)=>`<h2>${e(h)}</h2><p>${e(p)}</p>`;
const intro=(title,desc)=>`<section class="wrap page-intro"><p class="eyebrow">${e(c.tag)} / 中文资料</p><h1>${e(title)}</h1><p>${e(desc)}</p></section>`;
const block=s=>`<section class="wrap section prose">${s}</section>`;
const card=(title,desc,url)=>`<article class="guide-card"><h3>${e(title)}</h3><p>${e(desc)}</p><a class="text-link" href="${url}">查看${e(title)} →</a></article>`;
const guides=()=>`<div class="guide-grid">${articles.map(a=>card(a.title,a.description,'/tutorials/'+a.slug+'/')).join('')}</div>`;
const platform=[['windows','Windows','v2rayN','https://github.com/2dust/v2rayN/releases','在设置的系统信息中确认 x64 或 ARM64，再对照发行说明选择文件。'],['android','Android','v2rayNG','https://github.com/2dust/v2rayNG/releases','核对设备 ABI 和系统版本；APK 只用于安卓设备。安装后按应用提示确认 VPN 权限。'],['macos','macOS','v2rayN','https://github.com/2dust/v2rayN/releases','在关于本机查看芯片信息，区分 Apple Silicon 与 Intel，按发行说明检查系统要求。'],['ios','iPhone / iPad','Shadowrocket','https://apps.apple.com/us/app/shadowrocket/id932747118','通过 App Store 核对开发者、适用设备和当前价格，使用自己的 Apple 账户；不要下载所谓 iOS APK。']];
platform.push(['linux','Linux','v2rayN','https://github.com/2dust/v2rayN/releases','按发行版、架构与开发者发行说明选择对应安装包；兼容性以服务说明为准。']);
const devices=()=>`<div class="download-grid">${platform.map(p=>card(p[1]+' 下载',p[4],'/downloads/'+p[0]+'/')).join('')}</div>`;
async function page(route,title,desc,body,extra={}){await mkdir(path.join(output,route),{recursive:true});await writeFile(path.join(output,route,'index.html'),t.shell(title,desc,route,body,extra));routes.push({route,date:extra.dateModified});}
try{
for(const f of ['style.css','logo.svg','favicon.svg'])await copyFile('src/'+f,path.join(output,f));await writeFile(path.join(output,'site.js'),'/* Static guide: no account, payment or tracking scripts. */');
await page('/',c.title,c.description,`<section class="wrap hero"><div class="hero-grid"><div><p class="eyebrow">${e(c.tag)} / 中文指南</p><h1>${e(c.name)}<span>${e(c.hero[1])}</span></h1><p class="hero-description">${e(c.description)}</p><div class="actions"><a class="button" href="/downloads/">查看下载指引 →</a><a class="button secondary" href="/tutorials/">开始配置教程</a></div><p class="hero-foot">来源可查 · 步骤清晰 · 按设备阅读</p></div><aside class="hero-card"><p class="eyebrow">START HERE</p><h2>${e(c.focus)}</h2><ol><li>确认设备、软件和配置来源</li><li>按客户端要求导入或登录</li><li>更新配置并检查实际访问</li></ol><a class="text-link" href="/tutorials/import-subscription/">阅读完整设备检查表 →</a></aside></div></section><section class="wrap section"><h2>从你现在遇到的问题开始</h2><div class="guide-grid">${card('下载与安装','分清操作系统、架构和安装来源。','/downloads/')+card('订阅与配置','确认服务是否支持通用客户端，再选择导入方式。','/subscription/')+card('连接排查','记录错误环节，一次只调整一个变量。','/tutorials/connection-check/')}</div></section><section class="wrap section"><h2>按设备查找下载资料</h2><p>下列入口是通用客户端资料，并非 ${e(c.name)} 专用软件；兼容性以服务方说明为准。</p>${devices()}</section><section class="wrap section"><h2>配置与使用教程</h2>${guides()}</section><section class="wrap section"><h2>继续阅读</h2><div class="guide-grid">${card('套餐选择','核对付费总额、流量周期与使用限制。','/pricing/')+card('节点与速度','区分配置上限、延迟和实际吞吐。','/network/')+card('流媒体说明','按账号、设备、网络与内容地区逐项检查。','/streaming/')}</div></section>`);
const pages=[
['pricing','套餐选择与费用核对','购买前核对周期、额度与最终应付金额。',para('先核对总付款金额','月均价格不一定能按月购买。记录实际付款金额、对应月份、流量重置日期和是否自动续费；不要只比较首页展示的最低价。')+para('流量与设备限制','确认 GB 是每月重置还是整个周期共享，以及是否计算上下行、是否有流量倍率。设备上限通常与同时在线有关，应以账户说明为准。')+para('优惠和退款条件','优惠码只有在当前结账页面确认适用后才能算入预算。阅读新购、续费、周期和使用次数限制，并保存订单与退款条款。')+para('品牌名称不等于固定价格',`${c.name} 的名称或第三方介绍不能替代当前订单。本站不代收费用，不将示例数字作为现行报价。`)],
['network','节点线路与速度检查','用同一设备、同一网络和相同目标比较连接表现。',para('延迟不是下载速度','毫秒反映往返时间，Mbps 反映单位时间传输量。节点能响应延迟测试，不代表所有应用都能正常访问。')+para('固定测试条件','记录本地宽带、Wi-Fi 或移动网络、客户端版本、节点地区、时段和测试目标。关闭不必要的下载任务，一次只改变节点或网络中的一个因素。')+para('按用途选择地区','先选择与访问目标和服务规则相符的地区；物理距离只是影响因素之一。不要根据名称中的专线或高速字样推断实际线路质量。')+para('保留可重复的记录','先检查直连网络，再检查代理接管，最后比较不同节点。没有带时间和环境的测量记录，不给出固定速度保证。')],
['streaming','流媒体与应用访问说明','将网络可达性与账户、设备和内容地区分开排查。',para('网页能打开不等于能播放','页面加载、登录、获取片单和播放视频是不同环节。检查会员状态、设备兼容与播放错误码，记录具体失败步骤。')+para('地区与内容差异','片库和播放权限取决于平台内容授权、账户与所在地规则。切换节点并不构成可用性保证，不应据此承诺永久解锁。')+para('清晰度与缓冲','固定视频、清晰度和测试时段进行比较。下载速度、设备解码、无线信号和平台服务器都可能影响缓冲。')],
['subscription','订阅配置与账户说明','区分登录地址、订阅链接与客户端配置。',para('先确认接入方式',`${c.name}相关服务可能使用专用客户端或通用订阅。先阅读已有可信后台的接入说明，不将账号登录页直接当成订阅地址。`)+para('按顺序导入','先保存原配置，再选择服务支持的格式。添加订阅后执行更新，确认存在节点并选中正确配置，最后启动连接并测试一次普通请求。')+para('个人链接需要保密','订阅通常携带个人令牌。不要将完整链接提交到评论区、公开仓库或陌生转换站。疑似泄露时应在服务后台重置，再逐台更新设备。')],
['faq','常见问题','从下载、配置和设备环境开始定位问题。',para('是否可以直接在本站购买？','本站提供中文资料与下载来源指引，不处理订单和服务账户。购买与账户问题应通过你已经核实的服务入口处理。')+para('通用客户端一定兼容吗？','不一定。协议、订阅格式和服务接入规则都需要匹配；只有服务方明确支持时才使用对应客户端。')+para('更新订阅失败怎么办？','先检查链接是否完整、本地网络是否可用、账户是否有效，再查看客户端错误提示。二维码和复制内容都可能包含过期地址。')+para('为什么只有部分应用失败？','确认该应用是否遵循系统代理，检查分流规则、DNS 和应用缓存。保留一台正常设备作为对照有助于定位问题。')],
['about','关于本站与资料来源','了解网站的内容范围和编辑原则。',para('中文资料定位',`${c.domain} 是围绕 ${c.name} 相关使用问题整理的中文资料站。本站不代表第三方软件开发者或服务运营方，不提供其账户登录与付款入口。`)+para('内容如何整理','教程从系统、配置格式与检查步骤出发，原始软件资料链接至项目仓库或应用商店。涉及服务实时价格、节点状态和活动，以相应服务的可核实记录为准。')+para('区别说明与实测','安装和排查步骤是操作指引，不是付费服务的性能评测。本站没有用虚构用户评价、销量或速度数字作为推荐依据。')],
['privacy','隐私与外部链接','了解静态页面和第三方服务的数据边界。',para('本站页面','页面不要求注册，不收集订阅地址，也没有付款表单。当前页面未加入广告追踪脚本；托管与网络服务商可能为运行服务保留访问日志。')+para('外部链接','点击开发者仓库、应用商店或其他资料站会进入第三方服务，对方的数据处理规则独立适用。不要在不明页面输入原有密码或令牌。')],
['terms','使用说明与内容边界','按来源核对信息，并保留自己的配置与账户记录。',para('资料适用范围','通用教程不能覆盖所有系统版本与服务配置。更改网络设置前先备份，遇到不一致应查阅正在使用的软件发行说明。')+para('服务与付款','本站不代售订阅、不处理退款，不保证第三方服务的长期可用性。服务合同和付款条款以实际运营方公布并由用户接受的内容为准。')+para('合理使用','只访问本人有权使用的网络资源，遵守适用规则与相关服务条款，不公开传播他人的账户和订阅配置。')]
];
pages.push(['subscribe','开通前的信息核对','先确认可信服务入口、真实订单和适用条件。',para('本站不提供购买入口','本站为中文资料站，不代收款，也不替服务方确认现行价格、优惠或账户额度。请在自己已经核实的服务入口查看订单和条款。')+para('付款前保留记录','核对总付款、服务周期、流量计量、自动续费和退款条件；无法确认来源时不输入账户或付款资料。')]);
for(const [route,title,desc,body] of pages)await page('/'+route+'/',c.name+' '+title,c.name+'：'+desc,intro(title,desc)+block(body));
await page('/downloads/',c.name+' 下载中心与安装指引','按平台查找通用客户端原始发布页面，确认兼容性后再安装。',intro(c.name+' 下载与安装指引','先核对专用客户端的来源；以下为通用客户端资料，只有服务明确支持时才使用。')+`<section class="wrap section"><h2>选择设备平台</h2>${devices()}</section>`+block(para('软件下载来源','桌面端与安卓端链接至开发者 GitHub Releases，iPhone 与 iPad 链接至 App Store。本站不重新打包或托管第三方安装文件。')+'<p><a href="/downloads/">阅读安装包核对步骤</a></p>'));
for(const p of platform)await page('/downloads/'+p[0]+'/',c.name+' '+p[1]+' 下载说明',p[4],intro(p[1]+' 下载与安装',p[4])+block(para('先确认客户端适用范围',`${p[2]} 是独立的通用软件，并非 ${c.name} 专用客户端。请先确认服务支持的协议、配置格式和使用方式。`)+`<p><a class="button" href="${p[3]}">进入 ${e(p[2])} 原始发布页面 →</a></p>`+para('安装前记录','记录系统版本和芯片架构。下载后查看文件扩展名、发行说明和可用的签名信息；遇到安全警告先核对来源。')+para('安装后验证','先启动软件确认能正常运行，再导入自己的配置。允许必要权限后进行普通访问测试；不要同时启用多个代理软件。')+'<p><a href="/tutorials/import-subscription/">继续查看订阅导入步骤</a></p>'));
await page('/tutorials/',c.name+' 配置与使用教程','按下载、导入、验证和维护顺序阅读配置教程。',intro(c.name+' 使用教程','先完成一台设备的首次连接，再处理迁移、升级和故障排查。')+`<section class="wrap section"><h2>全部使用教程</h2>${guides()}</section>`);
for(const a of articles)await page('/tutorials/'+a.slug+'/',a.title+' | 中文指南',a.description,t.article(a),{'@type':'Article',headline:a.title,datePublished:a.date,dateModified:a.updated,author:{'@type':'Organization',name:a.author}});
await writeFile(path.join(output,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>${origin+r.route}</loc>${r.date?`<lastmod>${r.date}</lastmod>`:''}</url>`).join('')+'</urlset>');
await writeFile(path.join(output,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);await writeFile(path.join(output,'CNAME'),c.domain+'\n');await writeFile(path.join(output,'.nojekyll'),'');
await writeFile(path.join(output,'404.html'),t.shell('页面未找到 | '+c.name,'返回首页继续查看资料。','/404.html',intro('页面未找到','请通过导航查找下载或教程。')+block('<a href="/">返回首页</a>')).replace('index,follow,max-image-preview:large','noindex'));
await validateSite(output,origin);const dist=path.join(root,'dist');await rm(dist,{recursive:true,force:true});await rename(output,dist);console.log(`${c.domain}: ${routes.length} pages, ${articles.length} articles, links passed`);
}catch(error){await rm(output,{recursive:true,force:true});throw error;}
